name: Upload Rust Packages

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  upload-test-cgi:
        runs-on: ubuntu-latest
    strategy: 
      matrix:
        target: [ aarch64-unknown-linux-gnu,  x86_64-unknown-linux-gnu]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
    - name: Upload test-cgi to Github release
      run: |
        staging="test-cgi-${{github.event.release.tag_name}}-${{ matrix.platform }}"
        mkdir "$staging"
        cp target/release/${{ matrix.exec }} "$staging/"
        tar czf "$staging.tar.gz" "$staging"
        gh release upload ${{github.event.release.tag_name}} "$staging.tar.gz"
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
      shell: bash

